/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodosnumericos;

import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krawz
 */
public class MetodoSecante extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public MetodoSecante() {
        initComponents();
        setTitle("Método Secante");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTol = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtXi = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        txtIt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtX2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtXi2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tolerancia:");

        txtTol.setText("0");

        jLabel2.setText("x:");

        txtX.setText("0");

        jLabel3.setText("xi:");

        txtXi.setText("1");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtIt.setText("100");

        jLabel4.setText("Iteraciones:");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iteración", "X", "Xi", "Xr", "f(X)", "f(Xi)", "f(Xr)", "f(X)*f(Xr)", "f(Xi)*f(Xr)", "Ea"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iteración", "X", "Xi", "Xr", "f(X)", "f(Xi)", "f(Xr)", "f(X)*f(Xr)", "f(Xi)*f(Xr)", "Ea"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla1);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("x:");

        txtX2.setText("0.5");

        jLabel6.setText("xi:");

        txtXi2.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTol, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(btnCalcular)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtXi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtXi2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtIt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtXi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcular)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtTol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtXi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) tabla.getModel();
        double xm = Double.parseDouble(txtX.getText());
        double xi = Double.parseDouble(txtXi.getText());
        boolean terminar = false;
        int formula = 1;
        double xr, xrnueva = 0, ea;
        int iteracion = Integer.parseInt(txtIt.getText());
        double tolerancia = Double.parseDouble(txtTol.getText());
        xr = xi - ((f(xi, formula) * (xm - xi)) / (f(xm, formula) - f(xi, formula)));
        for (int x = 0; x < iteracion; x++) {

            if (f(xr, formula) == 0) {
                System.out.println("Operación:" + f(xm, formula) * f(xr, formula));
                System.out.println(xr + " es la raíz");
                System.out.println("Terminado por 0");
                terminar = true;
            }

            xm = xi;
            xi = xr;
            xrnueva = xi - ((f(xi, formula) * (xm - xi)) / (f(xm, formula) - f(xi, formula)));

            System.out.println("Xrnueva: " + xrnueva);
            System.out.println("Xr: " + xr);
            ea = Math.abs((xrnueva - xr) / xrnueva);
            System.out.println("Ea: " + ea);

            String res[] = {Integer.toString(x + 1), doubleToString(xm), doubleToString(xi), doubleToString(xr), doubleToString(f(xm, formula)),
                doubleToString(f(xi, formula)), doubleToString(f(xr, formula)), doubleToString(f(xm, formula) * f(xr, formula)),
                doubleToString(f(xi, formula) * f(xr, formula)), doubleToString(ea)};

            dm.addRow(res);

            if (terminar == true) {
                break;
            }

            if (Math.abs((xm - xr) / xm) <= tolerancia) {
                System.out.println(xm + " es la raíz");
                System.out.println("Terminado por tolerancia");
                break;
            }

//            if (ea <= tolerancia) {
//                System.out.println(xm + " es la raíz");
//                System.out.println("Terminado por tolerancia");
//                break;
//            }
            xr = xrnueva;
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm2 = (DefaultTableModel) tabla1.getModel();
        double xm = Double.parseDouble(txtX2.getText());
        double xi = Double.parseDouble(txtXi2.getText());
        boolean terminar = false;
        int formula = 2;
        double xr, xrnueva, ea;
        int iteracion = Integer.parseInt(txtIt.getText());
        double tolerancia = Double.parseDouble(txtTol.getText());
        xr = xi - ((f(xi, formula) * (xm - xi)) / (f(xm, formula) - f(xi, formula)));
        for (int x = 0; x < iteracion; x++) {

            if (f(xr, formula) == 0) {
                System.out.println("Operación:" + f(xm, formula) * f(xr, formula));
                System.out.println(xr + " es la raíz");
                System.out.println("Terminado por 0");
                terminar = true;
            }

            xm = xi;
            xi = xr;
            xrnueva = xi - ((f(xi, formula) * (xm - xi)) / (f(xm, formula) - f(xi, formula)));

            System.out.println("Xrnueva: " + xrnueva);
            System.out.println("Xr: " + xr);
            ea = Math.abs((xrnueva - xr) / xrnueva);
            System.out.println("Ea: " + ea);

            String res[] = {Integer.toString(x + 1), doubleToString(xm), doubleToString(xi), doubleToString(xr), doubleToString(f(xm, formula)),
                doubleToString(f(xi, formula)), doubleToString(f(xr, formula)), doubleToString(f(xm, formula) * f(xr, formula)),
                doubleToString(f(xi, formula) * f(xr, formula)), doubleToString(ea)};

            dm2.addRow(res);

            if (terminar == true) {
                break;
            }

            if (Math.abs((xm - xr) / xm) <= tolerancia) {
                System.out.println(xm + " es la raíz");
                System.out.println("Terminado por tolerancia");
                break;
            }

//            if (ea <= tolerancia) {
//                System.out.println(xm + " es la raíz");
//                System.out.println("Terminado por tolerancia");
//                break;
//            }
            xr = xrnueva;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static double f(double x, int numero) {
        if (numero == 1) {
            return ((Math.pow(Math.E, -x)) - x);
        } else {
            return (Math.log(Math.abs(x)));
        }
    }

    public static String doubleToString(Double d) {
        if (d == null) {
            return null;
        }
        if (d.isNaN() || d.isInfinite()) {
            return d.toString();
        }

        // pre java 8, a value of 0 would yield "0.0" below
        if (d.doubleValue() == 0) {
            return "0";
        }
        return new BigDecimal(d.toString()).stripTrailingZeros().toPlainString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodoSecante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodoSecante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodoSecante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodoSecante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodoSecante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField txtIt;
    private javax.swing.JTextField txtTol;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtX2;
    private javax.swing.JTextField txtXi;
    private javax.swing.JTextField txtXi2;
    // End of variables declaration//GEN-END:variables
}
